name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'benchmarks/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run benchmarks
      run: |
        if [ -d "benchmarks" ]; then
          dotnet run --project benchmarks/DotNetApiDiff.Benchmarks/DotNetApiDiff.Benchmarks.csproj -c Release
        else
          echo "No benchmarks directory found. Skipping benchmarks."
        fi
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: success() && hashFiles('BenchmarkDotNet.Artifacts/**') != ''
      with:
        name: benchmark-results
        path: BenchmarkDotNet.Artifacts/**